### PR TITLE
Link libdeflate for Linux builds

### LINKED ISSUE #1248: Build fails on Manjaro/Arch (and other systems using OpenCV with OpenEXR 3.2+) if libdeflate isn't explicitly linked
### Bug Description

When I compile Tahoma2D, following the Linux build instructions either as is or with a modified PKGBUILD, it always stops around 62% after it says it finished building something, e.g. `toonzqt` or `tnzstdfx`, with the error `make: *** [Makefile:136: all] Error 2`. If I try compiling again a few times, somehow it seems to get past that part and I can even get to 100% (after it says it finished building the `Tahoma2D` executable) but still have this error. Adding `LANG=C` and `VERBOSE=1` doesn't give any more helpful/meaningful output.

This has been a problem since around August or September, and I don't know what changed.

Edit: Possibly something to do with `openexr` updating from 3.1.11 to 3.2.0 and installing `libdeflate` as a dependency (has a linker error, usually further up around 42% or 43%, about undefined references in `libimage` to `libdeflate`).

### Steps to reproduce

1. Start building from command line, following instructions
2. Error occurs

### Relevant logs/screenshots

```
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_free_decompressor'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_alloc_compressor'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_zlib_decompress'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_zlib_compress_bound'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_zlib_compress'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_free_compressor'
/usr/bin/ld: ../lib/tahoma2d/libimage.so: undefined reference to `libdeflate_alloc_decompressor'
collect2: error: ld returned 1 exit status
```

### Software Version

Other (Specify below)

### Software Version Information

Commit 919d53815 (or whichever is latest at the time, since I try again with each commit)

### Operating System

Manjaro with Linux kernel 6.5.7

### Graphics Card

_No response_

### Drawing Tablet

_No response_

### PR DESCRIPTION
**Pull request by manongjohn**
Something changed in one of the package dependencies that is now installing libdeflate onto the Linux build environments in GitHub. This causes Linux builds to fail with the same messages as found in #1248.  We're still building using OpenEXR 2.3 so it appears somethings else we are currently building with now requires libdeflate.

This replaces PR #1274, and hopefully fixes #1248, which was the original attempt to fix linux builds but wasn't needed at the time since github builds were not failing.

I will merge as soon as I see that all checks have passed.

### CODE REVIEW

**Comment by manongjohn** [comment]
Seems GitHub wanted to play a joke on me...my other PR that failed due to libdeflate linking error, reran successfully without libdeflate linked in.  This is technically not needed now...well not at this moment at least.

Will merge it when checks are complete anyway.  It should at least fix #1248.
